# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormatPerformerTagsOptionsPage(object):
    def setupUi(self, FormatPerformerTagsOptionsPage):
        FormatPerformerTagsOptionsPage.setObjectName("FormatPerformerTagsOptionsPage")
        FormatPerformerTagsOptionsPage.resize(333, 516)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FormatPerformerTagsOptionsPage.sizePolicy().hasHeightForWidth())
        FormatPerformerTagsOptionsPage.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(FormatPerformerTagsOptionsPage)
        self.vboxlayout.setObjectName("vboxlayout")
        self.format_description = QtWidgets.QLabel(FormatPerformerTagsOptionsPage)
        self.format_description.setWordWrap(True)
        self.format_description.setObjectName("format_description")
        self.vboxlayout.addWidget(self.format_description)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem)
        self.groupBox_Words = QtWidgets.QGroupBox(FormatPerformerTagsOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Words.sizePolicy().hasHeightForWidth())
        self.groupBox_Words.setSizePolicy(sizePolicy)
        self.groupBox_Words.setObjectName("groupBox_Words")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_Words)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Words)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_Words)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_Words)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_Words)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_Words)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_Words)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.format_group_additional = QtWidgets.QSpinBox(self.groupBox_Words)
        self.format_group_additional.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.format_group_additional.setMinimum(1)
        self.format_group_additional.setMaximum(3)
        self.format_group_additional.setObjectName("format_group_additional")
        self.gridLayout_2.addWidget(self.format_group_additional, 1, 1, 1, 1)
        self.format_group_guest = QtWidgets.QSpinBox(self.groupBox_Words)
        self.format_group_guest.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.format_group_guest.setMinimum(1)
        self.format_group_guest.setMaximum(3)
        self.format_group_guest.setObjectName("format_group_guest")
        self.gridLayout_2.addWidget(self.format_group_guest, 2, 1, 1, 1)
        self.format_group_minor = QtWidgets.QSpinBox(self.groupBox_Words)
        self.format_group_minor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.format_group_minor.setMinimum(1)
        self.format_group_minor.setMaximum(3)
        self.format_group_minor.setObjectName("format_group_minor")
        self.gridLayout_2.addWidget(self.format_group_minor, 3, 1, 1, 1)
        self.format_group_solo = QtWidgets.QSpinBox(self.groupBox_Words)
        self.format_group_solo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.format_group_solo.setMinimum(1)
        self.format_group_solo.setMaximum(3)
        self.format_group_solo.setObjectName("format_group_solo")
        self.gridLayout_2.addWidget(self.format_group_solo, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.vboxlayout.addWidget(self.groupBox_Words)
        self.groupBox_Settings = QtWidgets.QGroupBox(FormatPerformerTagsOptionsPage)
        self.groupBox_Settings.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Settings.sizePolicy().hasHeightForWidth())
        self.groupBox_Settings.setSizePolicy(sizePolicy)
        self.groupBox_Settings.setObjectName("groupBox_Settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_Settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_Settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 3, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_9 = QtWidgets.QLabel(self.groupBox_Settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_7 = QtWidgets.QLabel(self.groupBox_Settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_11 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_Settings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_12 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_Settings)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 4, 0, 1, 1)
        self.format_group_2_start_char = QtWidgets.QLineEdit(self.groupBox_Settings)
        self.format_group_2_start_char.setObjectName("format_group_2_start_char")
        self.gridLayout_5.addWidget(self.format_group_2_start_char, 2, 2, 1, 1)
        self.format_group_1_start_char = QtWidgets.QLineEdit(self.groupBox_Settings)
        self.format_group_1_start_char.setObjectName("format_group_1_start_char")
        self.gridLayout_5.addWidget(self.format_group_1_start_char, 2, 1, 1, 1)
        self.format_group_3_start_char = QtWidgets.QLineEdit(self.groupBox_Settings)
        self.format_group_3_start_char.setObjectName("format_group_3_start_char")
        self.gridLayout_5.addWidget(self.format_group_3_start_char, 2, 3, 1, 1)
        self.format_group_1_end_char = QtWidgets.QLineEdit(self.groupBox_Settings)
        self.format_group_1_end_char.setObjectName("format_group_1_end_char")
        self.gridLayout_5.addWidget(self.format_group_1_end_char, 3, 1, 1, 1)
        self.format_group_2_end_char = QtWidgets.QLineEdit(self.groupBox_Settings)
        self.format_group_2_end_char.setObjectName("format_group_2_end_char")
        self.gridLayout_5.addWidget(self.format_group_2_end_char, 3, 2, 1, 1)
        self.format_group_3_end_char = QtWidgets.QLineEdit(self.groupBox_Settings)
        self.format_group_3_end_char.setObjectName("format_group_3_end_char")
        self.gridLayout_5.addWidget(self.format_group_3_end_char, 3, 3, 1, 1)
        self.format_group_3_sort_desc = QtWidgets.QCheckBox(self.groupBox_Settings)
        self.format_group_3_sort_desc.setText("")
        self.format_group_3_sort_desc.setObjectName("format_group_3_sort_desc")
        self.gridLayout_5.addWidget(self.format_group_3_sort_desc, 4, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_1_sort_desc = QtWidgets.QCheckBox(self.groupBox_Settings)
        self.format_group_1_sort_desc.setText("")
        self.format_group_1_sort_desc.setObjectName("format_group_1_sort_desc")
        self.gridLayout_5.addWidget(self.format_group_1_sort_desc, 4, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.format_group_2_sort_desc = QtWidgets.QCheckBox(self.groupBox_Settings)
        self.format_group_2_sort_desc.setText("")
        self.format_group_2_sort_desc.setObjectName("format_group_2_sort_desc")
        self.gridLayout_5.addWidget(self.format_group_2_sort_desc, 4, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.vboxlayout.addWidget(self.groupBox_Settings)
        spacerItem1 = QtWidgets.QSpacerItem(181, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)

        self.retranslateUi(FormatPerformerTagsOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(FormatPerformerTagsOptionsPage)

    def retranslateUi(self, FormatPerformerTagsOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.format_description.setText(_("<html><head/><body><p>These settings will determine the format for any <span style=\" font-weight:600;\">Performer</span> tags prepared. The format is divided into five parts: the performer; the instrument; and three user selectable groups for the extra information. This is set out as:</p><p align=\"center\">Group_1 Instrument Group_2: Performer Group_3</p><p>You can select the group in which each of the extra information words appears.</p><p>For each of the groups you can select the starting character, the ending character, and whether the group is sorted in ascending or descending order.</p></body></html>"))
        self.groupBox_Words.setTitle(_("Word Groups"))
        self.label_2.setText(_("Group"))
        self.label_4.setText(_("guest"))
        self.label_5.setText(_("minor"))
        self.label.setText(_("Keyword"))
        self.label_3.setText(_("additional"))
        self.label_6.setText(_("solo"))
        self.format_group_additional.setPrefix(_("Group "))
        self.format_group_guest.setPrefix(_("Group "))
        self.format_group_minor.setPrefix(_("Group "))
        self.format_group_solo.setPrefix(_("Group "))
        self.groupBox_Settings.setTitle(_("Group Settings"))
        self.label_10.setText(_("Group 3"))
        self.label_9.setText(_("Group 2"))
        self.label_7.setText(_("Setting"))
        self.label_11.setText(_("End Character(s)"))
        self.label_8.setText(_("Group 1"))
        self.label_12.setText(_("Start Character(s)"))
        self.label_13.setText(_("Sort Descending"))
        self.format_group_2_start_char.setText(_("("))
        self.format_group_3_start_char.setText(_("("))
        self.format_group_2_end_char.setText(_(")"))
        self.format_group_3_end_char.setText(_(")"))

