LANGUAGE_LIST = {
    'aar': "Afar",
    'abk': "Abchazisch",
    'ace': "Atjehs",
    'ach': "Akoli",
    'ada': "Adangme",
    'ady': "Adygees",
    'afh': "Afrihili",
    'afr': "Afrikaans",
    'ain': "Ainu",
    'aka': "Akan",
    'akk': "Akkadisch",
    'ale': "Aleoets",
    'alt': "Zuid-Altaïsch",
    'amh': "Amhaars",
    'ang': "Oudengels (ca. 450-1100)",
    'anp': "Angika",
    'ara': "Arabisch",
    'arc': "Aramees",
    'arg': "Aragonees",
    'arn': "Mapudungun (Araukaans)",
    'arp': "Arapaho",
    'arw': "Arawak",
    'asm': "Assamees",
    'ast': "Asturisch",
    'ava': "Avaars",
    'ave': "Avestisch",
    'awa': "Awadhi",
    'aym': "Aymara",
    'aze': "Azerbeidzjaans",
    'bak': "Basjkiers",
    'bal': "Beloetsji",
    'bam': "Bambara",
    'ban': "Balinees",
    'bas': "Basa",
    'bej': "Beja / Bedawi",
    'bel': "Wit-Russisch (Belarussisch)",
    'bem': "Bemba",
    'ben': "Bengaals",
    'bho': "Bhojpuri",
    'bik': "Bicol",
    'bin': "Edo (Bini)",
    'bis': "Bislama",
    'bla': "Siksika (Blackfoot)",
    'bod': "Tibetaans",
    'bos': "Bosnisch",
    'bra': "Braj",
    'bre': "Bretons",
    'bua': "Boerjatisch",
    'bug': "Buginees",
    'bul': "Bulgaars",
    'byn': "Blin / Bilin",
    'cad': "Caddo",
    'car': "Caribische talen",
    'cat': "Catalaans",
    'ceb': "Cebuano",
    'ces': "Tsjechisch",
    'cha': "Chamorro",
    'chb': "Chibcha",
    'che': "Tsjetsjeens",
    'chg': "Chagatai (Tsjagatai)",
    'chk': "Chuukees",
    'chm': "Mari",
    'chn': "Chinook",
    'cho': "Choctaw",
    'chp': "Chipewyan",
    'chr': "Cherokee",
    'chu': "Kerkslavisch",
    'chv': "Tsjoevasjisch",
    'chy': "Cheyenne",
    'cop': "Koptisch",
    'cor': "Cornisch",
    'cos': "Corsicaans",
    'cre': "Cree",
    'crh': "Krim-Tataars",
    'csb': "Kasjoebisch",
    'cym': "Welsh",
    'dak': "Dakota",
    'dan': "Deens",
    'dar': "Darginisch (Dargwa)",
    'del': "Unami (Delaware)",
    'den': "Slavey",
    'deu': "Duits",
    'dgr': "Dogrib",
    'din': "Dinka (Thuongjang)",
    'div': "Divehi",
    'doi': "Dogri",
    'dsb': "Nedersorbisch",
    'dua': "Duala",
    'dum': "Middelnederlands (ca.1050-1350)",
    'dyu': "Dioula",
    'dzo': "Dzongkha",
    'efi': "Efik",
    'egy': "Oud-Egyptisch",
    'eka': "Ekajuk",
    'ell': "Grieks",
    'elx': "Elamitisch",
    'eng': "Engels",
    'enm': "Middelengels (1100-1500)",
    'epo': "Esperanto",
    'est': "Estisch",
    'eus': "Baskisch",
    'ewe': "Ewe",
    'ewo': "Ewondo",
    'fan': "Fang",
    'fao': "Faeröers",
    'fas': "Perzisch (Farsi)",
    'fat': "Fante",
    'fij': "Fijisch",
    'fil': "Filipijns",
    'fin': "Fins",
    'fon': "Fon",
    'fra': "Frans",
    'frm': "Middelfrans (ca.1400-1600)",
    'fro': "Oudfrans (842-ca.1400)",
    'frr': "Noord-Fries",
    'frs': "Oosterlauwers Fries",
    'fry': "Westerlauwers Fries",
    'ful': "Fula",
    'fur': "Friulisch",
    'gaa': "Ga",
    'gay': "Gajo",
    'gba': "Gbaya",
    'gez': "Ge'ez",
    'gil': "Kiribatisch (Gilbertees)",
    'gla': "Schots-Gaelisch",
    'gle': "Iers",
    'glg': "Galicisch",
    'glv': "Manx-Gaelisch",
    'gmh': "Middelhoogduits (ca.1050-1500)",
    'goh': "Oudhoogduits (ca.750-1050)",
    'gon': "Gondi",
    'gor': "Gorontalo",
    'got': "Gotisch",
    'grb': "Grebo",
    'grc': "Oudgrieks (tot 1453)",
    'grn': "Guaraní",
    'gsw': "Zwitserduits",
    'guj': "Gujarati",
    'gwi': "Gwich’in",
    'hai': "Haida",
    'hat': "Haïtiaans Creools",
    'hau': "Hausa",
    'haw': "Hawaïaans",
    'hbs': "Servo-Kroatisch",
    'heb': "Hebreeuws",
    'her': "Herero",
    'hil': "Hiligaynon",
    'hin': "Hindi",
    'hit': "Hettitisch",
    'hmn': "Hmong",
    'hmo': "Hiri Motu",
    'hrv': "Kroatisch",
    'hsb': "Oppersorbisch",
    'hun': "Hongaars",
    'hup': "Hupa",
    'hye': "Armeens",
    'iba': "Iban",
    'ibo': "Igbo",
    'ido': "Ido",
    'iii': "Yi",
    'iku': "Inuktitut",
    'ile': "Interlingue",
    'ilo': "Ilokano",
    'ina': "Interlingua",
    'ind': "Indonesisch",
    'inh': "Ingoesjetisch",
    'ipk': "Inupiak",
    'isl': "IJslands",
    'ita': "Italiaans",
    'jav': "Javaans",
    'jbo': "Lojban",
    'jpn': "Japans",
    'jpr': "Judeo-Perzisch",
    'jrb': "Judeo-Arabisch",
    'kaa': "Karakalpaks",
    'kab': "Kabylisch",
    'kac': "Kachin (Jingpho)",
    'kal': "Groenlands",
    'kam': "Kamba",
    'kan': "Kannada (Kanarees, Kanara)",
    'kas': "Kasjmiri",
    'kat': "Georgisch",
    'kau': "Kanuri",
    'kaw': "Kawi",
    'kaz': "Kazachs",
    'kbd': "Kabardisch",
    'kha': "Khasi",
    'khm': "Khmer, Cambodjaans",
    'kho': "Hotanees",
    'kik': "Gikuyu",
    'kin': "Kinyarwanda",
    'kir': "Kirgizisch",
    'kmb': "Kimbundu",
    'kok': "Konkani",
    'kom': "Zurjeens (Komi)",
    'kon': "Kongo",
    'kor': "Koreaans",
    'kos': "Kosraeaans",
    'kpe': "Kpelle",
    'krc': "Karatsjaj-Balkarisch",
    'krl': "Karelisch",
    'kru': "Kurukh",
    'kua': "Kwanyama",
    'kum': "Kumyk",
    'kur': "Koerdisch",
    'kut': "Kutenai",
    'lad': "Ladino",
    'lah': "Lahnda",
    'lam': "Lamba",
    'lao': "Laotiaans",
    'lat': "Latijn",
    'lav': "Lets",
    'lez': "Lezgisch",
    'lim': "Limburgs",
    'lin': "Lingala",
    'lit': "Litouws",
    'lol': "Mongo",
    'loz': "Lozi",
    'ltz': "Luxemburgs",
    'lua': "Luba-Lulua",
    'lub': "Luba-Katanga",
    'lug': "Luganda",
    'lui': "Luiseno",
    'lun': "Lunda",
    'luo': "Luo (Kenia en Tanzania)",
    'lus': "Lushai",
    'mad': "Madoerees",
    'mag': "Magahi",
    'mah': "Marshallees",
    'mai': "Maithili",
    'mak': "Makassaars",
    'mal': "Malayalam",
    'man': "Mandinka",
    'mar': "Marathi",
    'mas': "Masai",
    'mdf': "Moksha",
    'mdr': "Mandar",
    'men': "Mende",
    'mga': "Middel-iers (900-1200)",
    'mic': "Micmac",
    'min': "Minangkabau",
    'mis': "niet gecodeerde talen",
    'mkd': "Macedonisch",
    'mlg': "Plateaumalagasi",
    'mlt': "Maltees",
    'mnc': "Mantsjoe",
    'mni': "Meitei (Manipuri)",
    'moh': "Mohawk",
    'mon': "Mongools",
    'mos': "Mossi",
    'mri': "Maori",
    'msa': "Maleis",
    'mul': "meerdere talen",
    'mus': "Muskogitalen",
    'mwl': "Mirandees",
    'mwr': "Marwari",
    'mya': "Birmaans, Birmees",
    'myv': "Erzja",
    'nap': "Napolitaans",
    'nau': "Nauruaans",
    'nav': "Navajo",
    'nbl': "Zuid-Ndebele",
    'nde': "Noord-Ndebele",
    'ndo': "Ndonga",
    'nds': "Nederduits",
    'nep': "Nepalees",
    'new': "Nepalbhasa (Newari)",
    'nia': "Nias",
    'niu': "Niueaans",
    'nld': "Nederlands",
    'nno': "Nynorsk (Nieuw-Noors)",
    'nob': "Bokmål-Noors",
    'nog': "Nogai",
    'non': "Oudnoords",
    'nor': "Noors",
    'nqo': "N'ko",
    'nso': "Pedi (Sepedi, Noord-Sothotisch)",
    'nwc': "Klassiek Newari (Klassiek Nepalbhasa)",
    'nya': "Nyanja",
    'nym': "Nyamwezi",
    'nyn': "Nyankole",
    'nyo': "Nyoro",
    'nzi': "Nzima",
    'oci': "Occitaans",
    'oji': "Ojibweg",
    'ori': "Odia (Oriya)",
    'orm': "Afaan Oromo",
    'osa': "Osage",
    'oss': "Ossetisch",
    'ota': "Osmaans (Ottomaans) (1500-1928)",
    'pag': "Pangasinan",
    'pal': "Pahlavi",
    'pam': "Pampanga",
    'pan': "Punjabi",
    'pap': "Papiaments",
    'pau': "Palaus",
    'peo': "Oudperzisch (ca.600-400 BC)",
    'phn': "Fenicisch",
    'pli': "Pali",
    'pol': "Pools",
    'pon': "Pohnpeiaans",
    'por': "Portugees",
    'pro': "Oudprovençaals (tot 1500) / Oud-occitaans (tot 1500)",
    'pus': "Pasjtoe",
    'que': "Quechua",
    'raj': "Rajasthani",
    'rap': "Rapa Nui",
    'rar': "Rarotongaans",
    'roh': "Reto-Romaans",
    'rom': "Romani",
    'ron': "Roemeens",
    'run': "Kirundi",
    'rup': "Aroemeens",
    'rus': "Russisch",
    'sad': "Sandawe",
    'sag': "Sango",
    'sah': "Jakoets",
    'sam': "Samaritaans",
    'san': "Sanskriet",
    'sas': "Sasak",
    'sat': "Santali",
    'scn': "Siciliaans",
    'sco': "Schots",
    'sel': "Selkoeps",
    'sga': "Oud-iers (tot 900)",
    'shn': "Shan",
    'sid': "Sidamo",
    'sin': "Singalees",
    'slk': "Slowaaks",
    'slv': "Sloveens",
    'sma': "Zuid-Samisch",
    'sme': "Noord-Samisch (Noord-Laps)",
    'smj': "Lule-Sami",
    'smn': "Inari-Sami",
    'smo': "Samoaans",
    'sms': "Skolt-Sami",
    'sna': "Shona",
    'snd': "Sindhi",
    'snk': "Soninke",
    'sog': "Sogdisch",
    'som': "Somalisch",
    'sot': "Zuid-Sotho",
    'spa': "Spaans",
    'sqi': "Albanees",
    'srd': "Sardijns",
    'srn': "Surinaams",
    'srp': "Servisch",
    'srr': "Sérères",
    'ssw': "Swazi",
    'suk': "Sukuma",
    'sun': "Soendanees",
    'sus': "Susu",
    'sux': "Soemerisch",
    'swa': "Swahili",
    'swe': "Zweeds",
    'syc': "Klassiek Syrisch",
    'syr': "Syrisch",
    'tah': "Tahitiaans",
    'tam': "Tamil",
    'tat': "Tataars",
    'tel': "Telugu, Teloegoe",
    'tem': "Timne",
    'ter': "Tereno",
    'tet': "Tetun",
    'tgk': "Tadzjieks",
    'tgl': "Tagalog",
    'tha': "Thai",
    'tig': "Tigre",
    'tir': "Tigrinya",
    'tiv': "Tiv",
    'tkl': "Tokelaus",
    'tlh': "Klingon",
    'tli': "Tlingit",
    'tmh': "Tamashek",
    'tog': "Tonga (Nyasa)",
    'ton': "Tongaans, Tonga",
    'tpi': "Tok Pisin",
    'tsi': "Tsimshiantalen",
    'tsn': "Tswana",
    'tso': "Tsonga",
    'tuk': "Turkmeens",
    'tum': "ChiTumbuka",
    'tur': "Turks",
    'tvl': "Tuvaluaans",
    'twi': "Twi",
    'tyv': "Toevaans",
    'udm': "Oedmoerts",
    'uga': "Ugaritisch",
    'uig': "Oeigoers",
    'ukr': "Oekraïens",
    'umb': "Umbundu",
    'und': "onbepaald",
    'urd': "Urdu",
    'uzb': "Oezbeeks",
    'vai': "Vai",
    'ven': "Venda",
    'vie': "Vietnamees",
    'vol': "Volapük, Volapuk",
    'vot': "Wotisch",
    'wal': "Walamo",
    'war': "Waray-Waray",
    'was': "Washo",
    'wln': "Waals",
    'wol': "Wolof",
    'xal': "Kalmuks",
    'xho': "Xhosa",
    'yao': "Yao",
    'yap': "Yapees",
    'yid': "Jiddisch",
    'yor': "Yoruba",
    'zap': "Zapoteeks",
    'zbl': "Blissymbolen",
    'zen': "Zenaga",
    'zha': "Zhuang, Tsjoeang",
    'zho': "Chinese talen",
    'zul': "Zoeloe",
    'zun': "Zuni",
    'zxx': "geen taalkundige inhoud",
    'zza': "Zazaki (Dimili / Kirdki / Kirmanckî / Zaza-Koerdisch)",
}
