LANGUAGE_LIST = {
    'aar': "afar",
    'abk': "abjaso",
    'ace': "Achinese",
    'ach': "Acoli",
    'ada': "Adangme",
    'ady': "adigué",
    'afh': "Afrihili",
    'afr': "Afrikaans",
    'ain': "Ainu",
    'aka': "acano",
    'akk': "acadio",
    'ale': "Aleut",
    'alt': "altay",
    'amh': "amárico",
    'ang': "Old English",
    'anp': "Angika",
    'ara': "árabe",
    'arc': "arameo",
    'arg': "aragonés",
    'arn': "mapudungun",
    'arp': "Arapaho",
    'arw': "Arawak",
    'asm': "asamés",
    'ast': "asturiano",
    'ava': "avaro",
    'ave': "Avestan",
    'awa': "awadhi",
    'aym': "aimara",
    'aze': "azerbayano",
    'bak': "baskir",
    'bal': "Baluchi",
    'bam': "Bambara",
    'ban': "balinés",
    'bas': "Basa",
    'bej': "beja",
    'bel': "bielorruso",
    'bem': "bemba",
    'ben': "bengalí",
    'bho': "bhojpurí",
    'bik': "bikol",
    'bin': "Bini",
    'bis': "bislama",
    'bla': "pies negros",
    'bod': "tibetano",
    'bos': "bosnio",
    'bra': "Braj",
    'bre': "bretón",
    'bua': "Buriat",
    'bug': "Buginese",
    'bul': "búlgaro",
    'byn': "Bilin",
    'cad': "caddo",
    'car': "Carib",
    'cat': "catalán",
    'ceb': "cebuano",
    'ces': "checo",
    'cha': "chamorro",
    'chb': "chibcha",
    'che': "checheno",
    'chg': "Chagatai",
    'chk': "Chuukese",
    'chm': "mari",
    'chn': "jerga chinook",
    'cho': "choctaw",
    'chp': "Chipewyan",
    'chr': "cheroqui",
    'chu': "eslavo eclesial",
    'chv': "chuvasio",
    'chy': "cheyén",
    'cnr': "montenegrino",
    'cop': "copto",
    'cor': "córnico",
    'cos': "corso",
    'cre': "cree",
    'crh': "tártaro de Crimea",
    'csb': "casubio",
    'cym': "galés",
    'dak': "Dakota",
    'dan': "danés",
    'dar': "dargínico",
    'del': "Delaware",
    'den': "Slave",
    'deu': "alemán",
    'dgr': "Dogrib",
    'din': "Dinka",
    'div': "maldivo",
    'doi': "dogri",
    'dsb': "bajo sorbio",
    'dua': "Duala",
    'dum': "neerlandés medio",
    'dyu': "Dyula",
    'dzo': "dzongkha",
    'efi': "Efik",
    'egy': "egipcio",
    'eka': "Ekajuk",
    'ell': "griego",
    'elx': "elamita",
    'eng': "inglés",
    'enm': "inglés medio",
    'epo': "esperanto",
    'est': "estonio",
    'eus': "euskera",
    'ewe': "efé",
    'ewo': "yaundé",
    'fan': "fangüé",
    'fao': "feroés",
    'fas': "persa",
    'fat': "Fanti",
    'fij': "fijiano",
    'fil': "filipino",
    'fin': "finés",
    'fon': "Fon",
    'fra': "francés",
    'frm': "francés medio",
    'fro': "francés antiguo",
    'frr': "Frisian, Northern",
    'frs': "Frisian, Eastern",
    'fry': "Frisian, Western",
    'ful': "Fulah",
    'fur': "friulo",
    'gaa': "Ga",
    'gay': "Gayo",
    'gba': "Gbaya",
    'gez': "ge'ez",
    'gil': "gilbertés",
    'gla': "gaélico escocés",
    'gle': "irlandés",
    'glg': "gallego",
    'glv': "manés",
    'gmh': "German, Middle High",
    'goh': "German, Old High",
    'gon': "gondi",
    'gor': "Gorontalo",
    'got': "gótico",
    'grb': "Grebo",
    'grc': "griego antiguo",
    'grn': "guaraní",
    'gsw': "Swiss German, Alemannic, Alsatian",
    'guj': "guyaratí",
    'gwi': "Gwich´in",
    'hai': "haida",
    'hat': "criollo haitiano",
    'hau': "hausa",
    'haw': "hawaiano",
    'heb': "hebreo",
    'her': "herero",
    'hil': "hiligainón",
    'hin': "Hindi",
    'hit': "Hittite",
    'hmn': "Hmong",
    'hmo': "Hiri Motu",
    'hrv': "croata",
    'hsb': "alto sorbio",
    'hun': "húngaro",
    'hup': "Hupa",
    'hye': "armenio",
    'iba': "Iban",
    'ibo': "igbo",
    'ido': "ido",
    'iii': "Yi, Sichuan",
    'iku': "inuktitut",
    'ile': "interlingue",
    'ilo': "Iloko",
    'ina': "interlingua",
    'ind': "indonesio",
    'inh': "inguso",
    'ipk': "inupiaq",
    'isl': "islandés",
    'ita': "italiano",
    'jav': "javanés",
    'jbo': "Lojban",
    'jpn': "japonés",
    'jpr': "judeo-persa",
    'jrb': "judeo-arabé",
    'kaa': "karakalpako",
    'kab': "cabilio",
    'kac': "Jingpho",
    'kal': "groenlandés",
    'kam': "Kamba",
    'kan': "canarés",
    'kas': "cachemir",
    'kat': "georgiano",
    'kau': "canurí",
    'kaw': "Kawi",
    'kaz': "kazajo",
    'kbd': "cabardiano",
    'kha': "jasí",
    'khm': "jemer",
    'kho': "Khotanese",
    'kik': "quicuyú",
    'kin': "ruandés",
    'kir': "kirguís",
    'kmb': "Kimbundu",
    'kok': "konkani",
    'kom': "komi",
    'kon': "kongo",
    'kor': "coreano",
    'kos': "Kosraean",
    'kpe': "Kpelle",
    'krc': "karachay-balkar",
    'krl': "carelio",
    'kru': "curuj",
    'kua': "Kuanyama",
    'kum': "kumyko",
    'kur': "kurdo",
    'kut': "Kutenai",
    'lad': "judeo-español",
    'lah': "lahnda",
    'lam': "Lamba",
    'lao': "laosiano",
    'lat': "latín",
    'lav': "letón",
    'lez': "lezguio",
    'lim': "Limburgish, Limburgan",
    'lin': "lingala",
    'lit': "lituano",
    'lol': "Mongo",
    'loz': "lozi",
    'ltz': "luxemburgués",
    'lua': "Luba-Lulua",
    'lub': "Luba-Katanga",
    'lug': "luganda",
    'lui': "luiseño",
    'lun': "Lunda",
    'luo': "Luo",
    'lus': "lusai",
    'mad': "Madurese",
    'mag': "magahi",
    'mah': "Marshall",
    'mai': "maithili",
    'mak': "Makasar",
    'mal': "malayalam",
    'man': "Mandingo",
    'mar': "maratí",
    'mas': "massaï",
    'mdf': "Moksha",
    'mdr': "Mandar",
    'men': "Mende",
    'mga': "irlandés medio",
    'mic': "micmac",
    'min': "Minangkabau",
    'mkd': "macedonio",
    'mlg': "malgache",
    'mlt': "maltés",
    'mnc': "Manchu",
    'mni': "manipurí",
    'moh': "mohawk",
    'mon': "mongol",
    'mos': "Mossi",
    'mri': "maorí",
    'msa': "malayo",
    'mus': "maskoki",
    'mwl': "mirandés",
    'mwr': "marwari",
    'mya': "birmano",
    'myv': "mordvino",
    'nap': "napolitano",
    'nau': "nauruano",
    'nav': "navajo",
    'nbl': "Ndebele, South",
    'nde': "Ndebele, North",
    'ndo': "Ndonga",
    'nds': "bajo sajón",
    'nep': "nepalí",
    'new': "Newari",
    'nia': "Nias",
    'niu': "Niuean",
    'nld': "neerlandés",
    'nno': "noruego nynorsk",
    'nob': "noruego bokmål",
    'nog': "nogay",
    'non': "antiguo nórdico",
    'nor': "noruego",
    'nqo': "N'Ko",
    'nso': "sepedi",
    'nwc': "Classical Newari",
    'nya': "ñanya",
    'nym': "nyamwezi",
    'nyn': "Nyankole",
    'nyo': "Nyoro",
    'nzi': "Nzima",
    'oci': "occitano",
    'oji': "ojibwa",
    'ori': "oriya",
    'orm': "oromo",
    'osa': "osage",
    'oss': "oseto",
    'ota': "Turco-otomano",
    'pag': "Pangasinan",
    'pal': "Pahlavi",
    'pam': "Pampanga",
    'pan': "panyabí",
    'pap': "papiamento",
    'pau': "palauano",
    'peo': "persa antiguo",
    'phn': "fenicio",
    'pli': "Pali",
    'pol': "polaco",
    'pon': "pohnpei",
    'por': "portugués",
    'pro': "provenzal antiguo",
    'pus': "pastú",
    'que': "quechua",
    'raj': "rayastaní",
    'rap': "Rapanui",
    'rar': "Rarotongan",
    'roh': "retorrománico",
    'rom': "Romany",
    'ron': "rumano",
    'run': "rundí",
    'rup': "aromùnico",
    'rus': "ruso",
    'sad': "Sandawe",
    'sag': "sango",
    'sah': "yakuto",
    'sam': "Aramaic, Samaritan",
    'san': "sánscrito",
    'sas': "Sasak",
    'sat': "santalí",
    'scn': "siciliano",
    'sco': "escocés",
    'sel': "selkup",
    'sga': "irlandés antiguo",
    'shn': "Shan",
    'sid': "Sidamo",
    'sin': "cingalés",
    'slk': "eslovaco",
    'slv': "esloveno",
    'sma': "Southern Sami",
    'sme': "Northern Sami",
    'smj': "Lule Sami",
    'smn': "Inari Sami",
    'smo': "samoano",
    'sms': "Skolt Sami",
    'sna': "sonés",
    'snd': "sindí",
    'snk': "Soninke",
    'sog': "Sogdian",
    'som': "somalí",
    'sot': "sesotho",
    'spa': "español",
    'sqi': "albanés",
    'srd': "sardo",
    'srn': "sranan",
    'srp': "serbio",
    'srr': "Serer",
    'ssw': "swati",
    'suk': "Sukuma",
    'sun': "sundanés",
    'sus': "Susu",
    'sux': "sumerio",
    'swa': "suahelí",
    'swe': "sueco",
    'syc': "Syriac, Classical",
    'syr': "Syriac",
    'tah': "tahitiano",
    'tam': "Tamil",
    'tat': "tártaro",
    'tel': "telugú",
    'tem': "Time",
    'ter': "Tereno",
    'tet': "Tetum",
    'tgk': "tayiko",
    'tgl': "tagalo",
    'tha': "tailandés",
    'tig': "tigré",
    'tir': "tigriña",
    'tiv': "Tiv",
    'tkl': "Tokelau",
    'tlh': "klingon",
    'tli': "tlingit",
    'tmh': "Tamashek",
    'tog': "Tonga",
    'ton': "tongano",
    'tpi': "Tok Pisin",
    'tsi': "tsimshian",
    'tsn': "setsuana",
    'tso': "tsonga",
    'tuk': "turcomano",
    'tum': "Tumbuka",
    'tur': "Turco",
    'tvl': "Tuvalu",
    'twi': "twi",
    'tyv': "Tuvinian",
    'udm': "udmurto",
    'uga': "ugarítico",
    'uig': "uigur",
    'ukr': "ucranio",
    'umb': "Umbundu",
    'urd': "Urdu",
    'uzb': "uzbeco",
    'vai': "Vai",
    'ven': "venda",
    'vie': "vietnamita",
    'vol': "volapük",
    'vot': "votio",
    'wal': "Wolaitta",
    'war': "Waray",
    'was': "washo",
    'wln': "Walloon",
    'wol': "volofo",
    'xal': "kalmyk",
    'xho': "xhosa",
    'yao': "Yao",
    'yap': "Yapese",
    'yid': "Yiddish",
    'yor': "Yoruba",
    'zap': "Zapotec",
    'zbl': "Blissymbols",
    'zen': "Zenaga",
    'zgh': "Standard Moroccan Tamazight",
    'zha': "Zhuang",
    'zho': "Chinese",
    'zul': "Zulu",
    'zun': "Zuni",
    'zza': "Zaza",
}
