LANGUAGE_LIST = {
    'aar': "afar",
    'abk': "abkhaze",
    'ace': "aceh",
    'ach': "acoli",
    'ada': "adangme",
    'ady': "adyghé",
    'afh': "afrihili",
    'afr': "Afrikaans",
    'ain': "aïnou",
    'aka': "akan",
    'akk': "akkadien",
    'ale': "aléoute",
    'alt': "altaï",
    'amh': "amharique",
    'ang': "Anglo-Saxon",
    'anp': "angika",
    'ara': "arabe",
    'arc': "araméen",
    'arg': "aragonais",
    'arn': "Araucan",
    'arp': "Arapaho",
    'arw': "Arawak",
    'asm': "assamais",
    'ast': "asturien",
    'ava': "avar",
    'ave': "avestique",
    'awa': "awadhi",
    'aym': "aymara",
    'aze': "azéri",
    'bak': "bachkir",
    'bal': "baloutchi",
    'bam': "bambara",
    'ban': "balinais",
    'bas': "basa",
    'bej': "bedja",
    'bel': "biélorusse",
    'bem': "bemba",
    'ben': "bengali",
    'bho': "bhojpurî",
    'bik': "bikol",
    'bin': "bini",
    'bis': "bichlamar",
    'bla': "pied-noir",
    'bod': "tibétain",
    'bos': "bosniaque",
    'bra': "braj",
    'bre': "breton",
    'bua': "bouriate",
    'bug': "bugi",
    'bul': "bulgare",
    'byn': "bilen",
    'cad': "caddo",
    'car': "carib",
    'cat': "catalan",
    'ceb': "cebuano",
    'ces': "tchèque",
    'cha': "chamorro",
    'chb': "chibcha",
    'che': "tchétchène",
    'chg': "djaghataï",
    'chk': "chuuk",
    'chm': "mari",
    'chn': "jargon chinook",
    'cho': "choctaw",
    'chp': "chipewyan",
    'chr': "cherokee",
    'chu': "slavon d'église vieux",
    'chv': "tchouvache",
    'chy': "cheyenne",
    'cnr': "monténégrin",
    'cop': "copte",
    'cor': "cornique",
    'cos': "corse",
    'cre': "cree",
    'crh': "tatar de Crimé",
    'csb': "cachoube",
    'cym': "gallois",
    'dak': "Dakota",
    'dan': "danois",
    'dar': "dargwa",
    'del': "Delaware",
    'den': "esclave",
    'deu': "allemand",
    'dgr': "dogrib",
    'din': "dinka",
    'div': "maldivien",
    'doi': "dogri",
    'dsb': "bas-sorabe",
    'dua': "douala",
    'dum': "néerlandais moyen",
    'dyu': "dioula",
    'dzo': "dzongkha",
    'efi': "efik",
    'egy': "égyptien",
    'eka': "ekajuk",
    'ell': "grec",
    'elx': "élamite",
    'eng': "anglais",
    'enm': "anglais moyen",
    'epo': "espéranto",
    'est': "estonien",
    'eus': "basque",
    'ewe': "éwé",
    'ewo': "éwondo",
    'fan': "fang",
    'fao': "féroïen",
    'fas': "persan",
    'fat': "fanti",
    'fij': "fidjien",
    'fil': "filipino",
    'fin': "finnois",
    'fon': "fon",
    'fra': "français",
    'frm': "moyen français",
    'fro': "ancien français",
    'frr': "frison septentrional",
    'frs': "frison",
    'fry': "frison",
    'ful': "peul",
    'fur': "frioulan",
    'gaa': "ga",
    'gay': "gayo",
    'gba': "gbaya",
    'gez': "guèze",
    'gil': "kiribati",
    'gla': "gaélique écossais",
    'gle': "irlandais",
    'glg': "galicien",
    'glv': "manx",
    'gmh': "moyen haut allemand",
    'goh': "vieux haut allemand",
    'gon': "gond",
    'gor': "gorontalo",
    'got': "gothique",
    'grb': "grebo",
    'grc': "grec ancien",
    'grn': "guarani",
    'gsw': "suisse alémanique, alémanique, alsacien",
    'guj': "gujarâtî",
    'gwi': "gwich´in",
    'hai': "haida",
    'hat': "haïtien",
    'hau': "haoussa",
    'haw': "hawaïen",
    'heb': "hébreu",
    'her': "herero",
    'hil': "hiligaynon",
    'hin': "Hindi",
    'hit': "hittite",
    'hmn': "hmong",
    'hmo': "hiri motu",
    'hrv': "croate",
    'hsb': "haut-sorabe",
    'hun': "hongrois",
    'hup': "hupa",
    'hye': "arménien",
    'iba': "iban",
    'ibo': "igbo",
    'ido': "ido",
    'iii': "yi de Sichuan",
    'iku': "inuktitut",
    'ile': "interlingue",
    'ilo': "ilocano",
    'ina': "interlingua",
    'ind': "indonésien",
    'inh': "ingouche",
    'ipk': "inupiaq",
    'isl': "islandais",
    'ita': "italien",
    'jav': "javanais",
    'jbo': "lojban",
    'jpn': "japonais",
    'jpr': "judéo-persan",
    'jrb': "judéo-arabe",
    'kaa': "karakalpak",
    'kab': "kabyle",
    'kac': "kachin",
    'kal': "groenlandais",
    'kam': "kamba",
    'kan': "kannada",
    'kas': "kashmiri",
    'kat': "géorgien",
    'kau': "kanouri",
    'kaw': "kawi",
    'kaz': "kazakh",
    'kbd': "kabardien",
    'kha': "khasi",
    'khm': "khmer",
    'kho': "khotanais",
    'kik': "kikuyu",
    'kin': "rwanda",
    'kir': "kirghize",
    'kmb': "kimbundu",
    'kok': "konkani",
    'kom': "kom",
    'kon': "kongo",
    'kor': "coréen",
    'kos': "kosrae",
    'kpe': "kpellé",
    'krc': "karatchaï balkar",
    'krl': "carélien",
    'kru': "kurukh",
    'kua': "kuanyama",
    'kum': "koumyk",
    'kur': "kurde",
    'kut': "kutenai",
    'lad': "judéo-espagnol",
    'lah': "lahnda",
    'lam': "lamba",
    'lao': "lao",
    'lat': "latin",
    'lav': "letton",
    'lez': "lezghien",
    'lim': "limbourgeois",
    'lin': "lingala",
    'lit': "lituanien",
    'lol': "mongo",
    'loz': "lozi",
    'ltz': "luxembourgeois",
    'lua': "luba-lulua",
    'lub': "luba-katanga",
    'lug': "ganda",
    'lui': "luiseno",
    'lun': "lunda",
    'luo': "luo",
    'lus': "lushai",
    'mad': "madourais",
    'mag': "magahi",
    'mah': "marshall",
    'mai': "maithili",
    'mak': "makassar",
    'mal': "malayalam",
    'man': "mandingue",
    'mar': "marathe",
    'mas': "massaï",
    'mdf': "moksa",
    'mdr': "mandar",
    'men': "mendé",
    'mga': "irlandais moyen",
    'mic': "micmac",
    'min': "minangkabau",
    'mkd': "macédonien",
    'mlg': "malgache",
    'mlt': "maltais",
    'mnc': "mandchou",
    'mni': "manipuri",
    'moh': "mohawk",
    'mon': "mongol",
    'mos': "moré",
    'mri': "maori",
    'msa': "malais",
    'mus': "muskogee",
    'mwl': "mirandais",
    'mwr': "marvari",
    'mya': "birman",
    'myv': "erza",
    'nap': "napolitain",
    'nau': "nauruan",
    'nav': "navaho",
    'nbl': "ndébélé du Sud",
    'nde': "ndébélé du Nord",
    'ndo': "ndonga",
    'nds': "bas allemand",
    'nep': "népalais",
    'new': "newari",
    'nia': "nias",
    'niu': "niué",
    'nld': "néerlandais",
    'nno': "norvégien nynorsk",
    'nob': "norvégien bokmål",
    'nog': "nogaï",
    'non': "vieux norrois",
    'nor': "norvégien",
    'nqo': "n'ko",
    'nso': "sotho du Nord",
    'nwc': "newari classique",
    'nya': "nyanja",
    'nym': "nyamwezi",
    'nyn': "nyankolé",
    'nyo': "nyoro",
    'nzi': "nzema",
    'oci': "occitan",
    'oji': "ojibwa",
    'ori': "oriya",
    'orm': "galla",
    'osa': "osage",
    'oss': "ossète",
    'ota': "Turc ottoman",
    'pag': "pangasinan",
    'pal': "pahlavi",
    'pam': "pampangan",
    'pan': "pendjabi",
    'pap': "papiamento",
    'pau': "palau",
    'peo': "vieux perse",
    'phn': "phénicien",
    'pli': "pali",
    'pol': "polonais",
    'pon': "pohnpei",
    'por': "portugais",
    'pro': "provençal ancien",
    'pus': "pachto",
    'que': "quechua",
    'raj': "rajasthani",
    'rap': "rapanui",
    'rar': "rarotonga",
    'roh': "rhéto-roman",
    'rom': "rromani <small>{''sic''}</small>",
    'ron': "roumain",
    'run': "rundi",
    'rup': "aromoun",
    'rus': "russe",
    'sad': "sandawe",
    'sag': "sango",
    'sah': "iakoute",
    'sam': "araméen samaritain",
    'san': "sanskrit",
    'sas': "sasak",
    'sat': "santal",
    'scn': "sicilien",
    'sco': "scot",
    'sel': "selkoup",
    'sga': "irlandais ancien",
    'shn': "chan",
    'sid': "sidamo",
    'sin': "singhalais",
    'slk': "slovaque",
    'slv': "slovène",
    'sma': "sami du Sud",
    'sme': "sami du Nord",
    'smj': "sami de Lule",
    'smn': "sami d'Inari",
    'smo': "samoan",
    'sms': "sami skolt",
    'sna': "shona",
    'snd': "sindhî",
    'snk': "soninké",
    'sog': "sogdien",
    'som': "somali",
    'sot': "sotho du Sud",
    'spa': "espagnol",
    'sqi': "albanais",
    'srd': "sarde",
    'srn': "créole surinamien",
    'srp': "serbe",
    'srr': "sérère",
    'ssw': "swati",
    'suk': "sukuma",
    'sun': "soundanais",
    'sus': "soussou",
    'sux': "sumérien",
    'swa': "swahili",
    'swe': "suédois",
    'syc': "syriaque classique",
    'syr': "syriaque",
    'tah': "tahitien",
    'tam': "tamoul",
    'tat': "tatar",
    'tel': "télougou",
    'tem': "temne",
    'ter': "tereno",
    'tet': "tetum",
    'tgk': "tadjik",
    'tgl': "Tagalog",
    'tha': "thaï",
    'tig': "tigré",
    'tir': "tigrigna",
    'tiv': "tiv",
    'tkl': "Tokelau",
    'tlh': "klingon",
    'tli': "tlingit",
    'tmh': "tamacheq",
    'tog': "Tonga",
    'ton': "Tongan",
    'tpi': "tok pisin",
    'tsi': "tsimshian",
    'tsn': "tswana",
    'tso': "tsonga",
    'tuk': "turkmène",
    'tum': "tumbuka",
    'tur': "Turc",
    'tvl': "Tuvalu",
    'twi': "twi",
    'tyv': "touva",
    'udm': "oudmourte",
    'uga': "ougaritique",
    'uig': "ouïgour",
    'ukr': "ukrainien",
    'umb': "umbundu",
    'urd': "ourdou",
    'uzb': "ouzbek",
    'vai': "vaï",
    'ven': "venda",
    'vie': "vietnamien",
    'vol': "volapük",
    'vot': "vote",
    'wal': "wolaitta",
    'war': "waray",
    'was': "washo",
    'wln': "wallon",
    'wol': "wolof",
    'xal': "kalmouk",
    'xho': "xhosa",
    'yao': "yao",
    'yap': "yapois",
    'yid': "Yiddish",
    'yor': "yoruba",
    'zap': "zapotèque",
    'zbl': "symboles Bliss",
    'zen': "zenaga",
    'zgh': "amazighe standard marocain",
    'zha': "zhuang",
    'zho': "chinois",
    'zul': "zoulou",
    'zun': "zuni",
    'zza': "zaza",
}
