LANGUAGE_LIST = {
    'aar': "Afar",
    'abk': "Abkhazian",
    'ace': "Achinese",
    'ach': "Acoli",
    'ada': "Adangme",
    'ady': "Adyghe",
    'afh': "Afrihili",
    'afr': "Afrikaans",
    'ain': "Ainu",
    'aka': "Akan",
    'akk': "Akkadian",
    'ale': "Aleut",
    'alt': "Altai",
    'amh': "Amharic",
    'ang': "Old English",
    'anp': "Angika",
    'ara': "Arabic",
    'arc': "Aramaic",
    'arg': "Aragonese",
    'arn': "Araucanian",
    'arp': "Arapaho",
    'arw': "Arawak",
    'asm': "Assamese",
    'ast': "Asturian",
    'ava': "Avaric",
    'ave': "Avestan",
    'awa': "Awadhi",
    'aym': "Aymara",
    'aze': "Azerbaijani",
    'bak': "Bashkir",
    'bal': "Baluchi",
    'bam': "Bambara",
    'ban': "Balinese",
    'bas': "Basa",
    'bej': "Beja",
    'bel': "Belarusian",
    'bem': "Bemba",
    'ben': "Bengali",
    'bho': "Bhojpuri",
    'bik': "Bikol",
    'bin': "Bini",
    'bis': "Bislama",
    'bla': "Blackfoot",
    'bod': "Tibetan",
    'bos': "Bosnian",
    'bra': "Braj",
    'bre': "Breton",
    'bua': "Buriat",
    'bug': "Buginese",
    'bul': "Bulgarian",
    'byn': "Bilin",
    'cad': "Caddo",
    'car': "Carib",
    'cat': "Catalan",
    'ceb': "Cebuano",
    'ces': "Czech",
    'cha': "Chamorro",
    'chb': "Chibcha",
    'che': "Chechen",
    'chg': "Chagatai",
    'chk': "Chuukese",
    'chm': "Mari",
    'chn': "Chinook jargon",
    'cho': "Choctaw",
    'chp': "Chipewyan",
    'chr': "Cherokee",
    'chu': "Old Church Slavonic",
    'chv': "Chuvash",
    'chy': "Cheyenne",
    'cnr': "Montenegrin",
    'cop': "Coptic",
    'cor': "Cornish",
    'cos': "Corsican",
    'cre': "Cree",
    'crh': "Crimean Tatar",
    'csb': "Kashubian",
    'cym': "Welsh",
    'dak': "Dakota",
    'dan': "Danish",
    'dar': "Dargwa",
    'del': "Delaware",
    'den': "Slave",
    'deu': "German",
    'dgr': "Dogrib",
    'din': "Dinka",
    'div': "Divehi",
    'doi': "Dogri",
    'dsb': "Sorbian, Lower",
    'dua': "Duala",
    'dum': "Dutch, Middle",
    'dyu': "Dyula",
    'dzo': "Dzongkha",
    'efi': "Efik",
    'egy': "Egyptian",
    'eka': "Ekajuk",
    'ell': "Greek",
    'elx': "Elamite",
    'eng': "English",
    'enm': "English, Middle",
    'epo': "Esperanto",
    'est': "Estonian",
    'eus': "Basque",
    'ewe': "Ewe",
    'ewo': "Ewondo",
    'fan': "Fang",
    'fao': "Faroese",
    'fas': "Persian",
    'fat': "Fanti",
    'fij': "Fijian",
    'fil': "Filipino",
    'fin': "Finnish",
    'fon': "Fon",
    'fra': "French",
    'frm': "French, Middle",
    'fro': "French, Old",
    'frr': "Frisian, Northern",
    'frs': "Frisian, Eastern",
    'fry': "Frisian, Western",
    'ful': "Fulah",
    'fur': "Friulian",
    'gaa': "Ga",
    'gay': "Gayo",
    'gba': "Gbaya",
    'gez': "Geez",
    'gil': "Gilbertese",
    'gla': "Gaelic",
    'gle': "Irish",
    'glg': "Galician",
    'glv': "Manx",
    'gmh': "German, Middle High",
    'goh': "German, Old High",
    'gon': "Gondi",
    'gor': "Gorontalo",
    'got': "Gothic",
    'grb': "Grebo",
    'grc': "Greek, Ancient",
    'grn': "Guarani",
    'gsw': "Swiss German, Alemannic, Alsatian",
    'guj': "Gujarati",
    'gwi': "Gwich´in",
    'hai': "Haida",
    'hat': "Haitian",
    'hau': "Hausa",
    'haw': "Hawaiian",
    'heb': "Hebrew",
    'her': "Herero",
    'hil': "Hiligaynon",
    'hin': "Hindi",
    'hit': "Hittite",
    'hmn': "Hmong",
    'hmo': "Hiri Motu",
    'hrv': "Croatian",
    'hsb': "Sorbian, Upper",
    'hun': "Hungarian",
    'hup': "Hupa",
    'hye': "Armenian",
    'iba': "Iban",
    'ibo': "Igbo",
    'ido': "Ido",
    'iii': "Yi, Sichuan",
    'iku': "Inuktitut",
    'ile': "Interlingue",
    'ilo': "Iloko",
    'ina': "Interlingua",
    'ind': "Indonesian",
    'inh': "Ingush",
    'ipk': "Inupiaq",
    'isl': "Icelandic",
    'ita': "Italian",
    'jav': "Javanese",
    'jbo': "Lojban",
    'jpn': "Japanese",
    'jpr': "Judeo-Persian",
    'jrb': "Judeo-Arabic",
    'kaa': "Karakalpak",
    'kab': "Kabyle",
    'kac': "Jingpho",
    'kal': "Kalaallisut",
    'kam': "Kamba",
    'kan': "Kannada",
    'kas': "Kashmiri",
    'kat': "Georgian",
    'kau': "Kanuri",
    'kaw': "Kawi",
    'kaz': "Kazakh",
    'kbd': "Kabardian",
    'kha': "Khasi",
    'khm': "Khmer",
    'kho': "Khotanese",
    'kik': "Kikuyu",
    'kin': "Kinyarwanda",
    'kir': "Kyrgyz",
    'kmb': "Kimbundu",
    'kok': "Konkani",
    'kom': "Komi",
    'kon': "Kongo",
    'kor': "Korean",
    'kos': "Kosraean",
    'kpe': "Kpelle",
    'krc': "Karachay-Balkar",
    'krl': "Karelian",
    'kru': "Kurukh",
    'kua': "Kuanyama",
    'kum': "Kumyk",
    'kur': "Kurdish",
    'kut': "Kutenai",
    'lad': "Ladino",
    'lah': "Lahnda",
    'lam': "Lamba",
    'lao': "Lao",
    'lat': "Latin",
    'lav': "Latvian",
    'lez': "Lezghian",
    'lim': "Limburgish, Limburgan",
    'lin': "Lingala",
    'lit': "Lithuanian",
    'lol': "Mongo",
    'loz': "Lozi",
    'ltz': "Luxembourgish",
    'lua': "Luba-Lulua",
    'lub': "Luba-Katanga",
    'lug': "Luganda",
    'lui': "Luiseno",
    'lun': "Lunda",
    'luo': "Luo",
    'lus': "Lushai",
    'mad': "Madurese",
    'mag': "Magahi",
    'mah': "Marshall",
    'mai': "Maithili",
    'mak': "Makasar",
    'mal': "Malayalam",
    'man': "Mandingo",
    'mar': "Marathi",
    'mas': "Masai",
    'mdf': "Moksha",
    'mdr': "Mandar",
    'men': "Mende",
    'mga': "Irish, Middle",
    'mic': "Micmac",
    'min': "Minangkabau",
    'mkd': "Macedonian",
    'mlg': "Malagasy",
    'mlt': "Maltese",
    'mnc': "Manchu",
    'mni': "Meitei",
    'moh': "Mohawk",
    'mon': "Mongolian",
    'mos': "Mossi",
    'mri': "Maori",
    'msa': "Malay",
    'mus': "Creek",
    'mwl': "Mirandese",
    'mwr': "Marwari",
    'mya': "Burmese",
    'myv': "Erzya",
    'nap': "Neapolitan",
    'nau': "Nauru",
    'nav': "Navajo",
    'nbl': "Ndebele, South",
    'nde': "Ndebele, North",
    'ndo': "Ndonga",
    'nds': "Low German",
    'nep': "Nepali",
    'new': "Newari",
    'nia': "Nias",
    'niu': "Niuean",
    'nld': "Dutch",
    'nno': "Norwegian Nynorsk",
    'nob': "Norwegian Bokmål",
    'nog': "Nogai",
    'non': "Norse, Old",
    'nor': "Norwegian",
    'nqo': "N'Ko",
    'nso': "Northern Sotho, Pedi",
    'nwc': "Classical Newari",
    'nya': "Chichewa",
    'nym': "Nyamwezi",
    'nyn': "Nyankole",
    'nyo': "Nyoro",
    'nzi': "Nzima",
    'oci': "Occitan",
    'oji': "Ojibwa",
    'ori': "Oriya",
    'orm': "Oromo",
    'osa': "Osage",
    'oss': "Ossetian",
    'ota': "Turkish, Ottoman",
    'pag': "Pangasinan",
    'pal': "Pahlavi",
    'pam': "Pampanga",
    'pan': "Panjabi",
    'pap': "Papiamento",
    'pau': "Palauan",
    'peo': "Persian, Old",
    'phn': "Phoenician",
    'pli': "Pali",
    'pol': "Polish",
    'pon': "Pohnpeian",
    'por': "Portuguese",
    'pro': "Provençal, Old",
    'pus': "Pushto",
    'que': "Quechua",
    'raj': "Rajasthani",
    'rap': "Rapanui",
    'rar': "Rarotongan",
    'roh': "Raeto-Romance",
    'rom': "Romany",
    'ron': "Romanian",
    'run': "Rundi",
    'rup': "Aromanian",
    'rus': "Russian",
    'sad': "Sandawe",
    'sag': "Sango",
    'sah': "Sakha",
    'sam': "Aramaic, Samaritan",
    'san': "Sanskrit",
    'sas': "Sasak",
    'sat': "Santali",
    'scn': "Sicilian",
    'sco': "Scots",
    'sel': "Selkup",
    'sga': "Old Irish",
    'shn': "Shan",
    'sid': "Sidamo",
    'sin': "Sinhala",
    'slk': "Slovak",
    'slv': "Slovenian",
    'sma': "Southern Sami",
    'sme': "Northern Sami",
    'smj': "Lule Sami",
    'smn': "Inari Sami",
    'smo': "Samoan",
    'sms': "Skolt Sami",
    'sna': "Shona",
    'snd': "Sindhi",
    'snk': "Soninke",
    'sog': "Sogdian",
    'som': "Somali",
    'sot': "Sotho, Southern",
    'spa': "Spanish",
    'sqi': "Albanian",
    'srd': "Sardinian",
    'srn': "Sranan",
    'srp': "Serbian",
    'srr': "Serer",
    'ssw': "Swati",
    'suk': "Sukuma",
    'sun': "Sundanese",
    'sus': "Susu",
    'sux': "Sumerian",
    'swa': "Swahili",
    'swe': "Swedish",
    'syc': "Syriac, Classical",
    'syr': "Syriac",
    'tah': "Tahitian",
    'tam': "Tamil",
    'tat': "Tatar",
    'tel': "Telugu",
    'tem': "Time",
    'ter': "Tereno",
    'tet': "Tetum",
    'tgk': "Tajik",
    'tgl': "Tagalog",
    'tha': "Thai",
    'tig': "Tigre",
    'tir': "Tigrinya",
    'tiv': "Tiv",
    'tkl': "Tokelau",
    'tlh': "Klingon",
    'tli': "Tlingit",
    'tmh': "Tamashek",
    'tog': "Tonga",
    'ton': "Tonga",
    'tpi': "Tok Pisin",
    'tsi': "Tsimshian",
    'tsn': "Tswana",
    'tso': "Tsonga",
    'tuk': "Turkmen",
    'tum': "Tumbuka",
    'tur': "Turkish",
    'tvl': "Tuvalu",
    'twi': "Twi",
    'tyv': "Tuvinian",
    'udm': "Udmurt",
    'uga': "Ugaritic",
    'uig': "Uighur",
    'ukr': "Ukrainian",
    'umb': "Umbundu",
    'urd': "Urdu",
    'uzb': "Uzbek",
    'vai': "Vai",
    'ven': "Venda",
    'vie': "Vietnamese",
    'vol': "Volapük",
    'vot': "Votic",
    'wal': "Wolaitta",
    'war': "Waray",
    'was': "Washo",
    'wln': "Walloon",
    'wol': "Wolof",
    'xal': "Kalmyk",
    'xho': "Xhosa",
    'yao': "Yao",
    'yap': "Yapese",
    'yid': "Yiddish",
    'yor': "Yoruba",
    'zap': "Zapotec",
    'zbl': "Blissymbols",
    'zen': "Zenaga",
    'zgh': "Standard Moroccan Tamazight",
    'zha': "Zhuang",
    'zho': "Chinese",
    'zul': "Zulu",
    'zun': "Zuni",
    'zza': "Zaza",
}
